---
galaxy_info:
  author: Your Name
  description: A simple role to install and start Nginx.
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - bionic