---
driver:
  name: vagrant

platforms:
  - name: ubuntu-20.04
    box: ubuntu/focal64
    memory: 2048
    cpus: 2

provisioner:
  name: ansible
  playbook: playbook.yml

verifier:
  name: ansible
  playbook: verify.yml